# Scipy and Numpy

## 2. Numpy
### 2.1. NumPy Arrays

In [1]:
import numpy as np
import timeit

In [2]:
# Create an array with 10^7 elements.
arr = np.arange(1e7)

# Converting ndarray to list
larr = arr.tolist()

# Lists cannot by default broadcast,
# so a function is coded to emulate
# what an ndarray can do.

def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar
    return alist

In [3]:
%%time

arr = arr * 1.1
pass

CPU times: user 24.1 ms, sys: 39.3 ms, total: 63.4 ms
Wall time: 61.7 ms


In [4]:
%%time 

list_times(larr, 1.1)
pass

CPU times: user 1.3 s, sys: 453 µs, total: 1.3 s
Wall time: 1.3 s


In [5]:
# Creating a 3D numpy array
arr = np.zeros((3,3,3))

try: 
    # Trying to convert array to a matrix, which will not work
    mat = np.matrix(arr)
except ValueError as e: 
    print(str(e))

# "ValueError: shape too large to be a matrix."

shape too large to be a matrix.


#### 2.1.1 Array Creation and Data Typing

In [6]:
%%time
# First we create a list and then
# wrap it with the np.array() function.
alist = [1, 2, 3]
arr = np.array(alist)
print(arr)

[1 2 3]
CPU times: user 1 ms, sys: 92 µs, total: 1.09 ms
Wall time: 1.77 ms


In [7]:
%%time
# Creating an array of zeros with five elements
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]
CPU times: user 1.71 ms, sys: 158 µs, total: 1.87 ms
Wall time: 5.55 ms


In [8]:
%%time
# What if we want to create an array going from 0 to 100?
arr = np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
CPU times: user 1.89 ms, sys: 0 ns, total: 1.89 ms
Wall time: 3.64 ms


In [9]:
%%time
# Or 10 to 100?
arr = np.arange(10,100)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
CPU times: user 977 µs, sys: 91 µs, total: 1.07 ms
Wall time: 1.08 ms


In [10]:
%%time
# If you want 100 steps from 0 to 1...
arr = np.linspace(0, 1, 100)
print(arr)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [11]:
%%time
# Or if you want to generate an array from 1 to 10
# in log10 space in 100 steps...
arr = np.logspace(0, 1, 100, base=10.0)
print(arr)

[ 1.          1.02353102  1.04761575  1.07226722  1.09749877  1.12332403
  1.149757    1.17681195  1.20450354  1.23284674  1.26185688  1.29154967
  1.32194115  1.35304777  1.38488637  1.41747416  1.45082878  1.48496826
  1.51991108  1.55567614  1.59228279  1.62975083  1.66810054  1.70735265
  1.7475284   1.78864953  1.83073828  1.87381742  1.91791026  1.96304065
  2.009233    2.05651231  2.10490414  2.15443469  2.20513074  2.25701972
  2.3101297   2.36448941  2.42012826  2.47707636  2.53536449  2.59502421
  2.65608778  2.71858824  2.7825594   2.84803587  2.91505306  2.98364724
  3.05385551  3.12571585  3.19926714  3.27454916  3.35160265  3.43046929
  3.51119173  3.59381366  3.67837977  3.76493581  3.85352859  3.94420606
  4.03701726  4.1320124   4.22924287  4.32876128  4.43062146  4.53487851
  4.64158883  4.75081016  4.86260158  4.97702356  5.09413801  5.21400829
  5.33669923  5.46227722  5.59081018  5.72236766  5.85702082  5.9948425
  6.13590727  6.28029144  6.42807312  6.57933225  6.

In [12]:
%%time
# Creating a 5x5 array of zeros (an image)
image = np.zeros((5,5))
print(image)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
CPU times: user 1.4 ms, sys: 0 ns, total: 1.4 ms
Wall time: 1.73 ms


In [13]:
%%time
# Creating a 5x5x5 cube of 1's
# The astype() method sets the array with integer elements.
cube = np.zeros((5,5,5)).astype(int) + 1
print(cube)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
CPU times: user 2.65 ms, sys: 249 µs, total: 2.89 ms
Wall time: 2.23 ms


In [14]:
%%time
# Or even simpler with 16-bit floating-point precision...
cube = np.ones((5, 5, 5)).astype(np.float16)
print(cube)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
CPU times: user 121 ms, sys: 0 ns, total: 121 ms
Wall time: 120 ms


In [15]:
# Array of zero integers
arr = np.zeros(2, dtype=int)
print(arr)

[0 0]


In [16]:
# Array of zero floats
arr = np.zeros(2, dtype=np.float32)
print(arr)

[0. 0.]


##### Reshape

In [17]:
# Creating an array with elements from 0 to 999
arr1d = np.arange(27)
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [18]:
# Now reshaping the array to a 10x10x10 3D array
arr3d = arr1d.reshape((3,3,3))
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [19]:
# The reshape command can alternatively be called this way
arr3d = np.reshape(arr1d, (3, 3, 3))
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [20]:
# Inversely, we can flatten arrays
arr4d = np.zeros((3, 3, 3, 3))
arr1d = arr4d.ravel()
print(arr1d.shape)
print(arr1d)

(81,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2.1.2 Record Arrays

In [21]:
# Creating an array of zeros and defining column types
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
toadd = [(1,2.,'Hello'),(2,3.,"World")]
recarr[:] = toadd

In [22]:
recarr

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [41]:
# Creating an array of zeros and defining column types
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
# Now creating the columns we want to put
# in the recarray
col1 = np.arange(2) + 1
col2 = np.arange(2, dtype=np.float32)
col3 = ['Hello', 'World']
# Here we create a list of tuples that is
# identical to the previous toadd list.
toadd = list(zip(col1, col2, col3))

print(toadd)

[(1, 0.0, 'Hello'), (2, 1.0, 'World')]


In [43]:
# Assigning values to recarr
recarr[:] = toadd

In [44]:
# Assigning names to each column, which
# are now by default called 'f0', 'f1', and 'f2'.
recarr.dtype.names = ('Integers' , 'Floats', 'Strings')
recarr

array([(1, 0., b'Hello'), (2, 1., b'World')],
      dtype=[('Integers', '<i4'), ('Floats', '<f4'), ('Strings', 'S10')])

In [45]:
# If we want to access one of the columns by its name, we
# can do the following.
recarr['Integers']

array([1, 2], dtype=int32)

In [46]:
# array([1, 2], dtype=int32)
recarr

array([(1, 0., b'Hello'), (2, 1., b'World')],
      dtype=[('Integers', '<i4'), ('Floats', '<f4'), ('Strings', 'S10')])

#### 2.1.3 Indexing and Slicing

In [ ]:
alist=[[1,2],[3,4]]
# To return the (0,1) element we must index as shown below.
alist[0][1]

In [ ]:
# Converting the list defined above into an array
arr = np.array(alist)

In [ ]:
# To return the (0,1) element we use ...
arr[0,1]

In [ ]:
# Now to access the last column, we simply use ...
arr[:,1]

In [40]:
# Accessing the columns is achieved in the same way,
# which is the bottom row.
arr[1,:]

array([3, 4])

In [48]:
# Creating an array
arr = np.arange(5)
print(arr)

array([0, 1, 2, 3, 4])

In [50]:
# Creating the index array
index = np.where(arr > 2)
print(index)

(array([3, 4]),)


In [52]:
# Creating the desired array
new_arr = arr[index]
print(new_arr)

[3 4]


In [53]:
# We use the previous array
new_arr = np.delete(arr, index)
print(new_arr)

[0 1 2]


In [55]:
index = arr > 2
print(index)

[False False False  True  True]


In [56]:
new_arr = arr[index]
print(new_arr)

[3 4]


### 2.2 Boolean Statements and NumPy Arrays

In [57]:
# Creating an image
img1 = np.zeros((20, 20)) + 3
img1[4:-4, 4:-4] = 6
img1[7:-7, 7:-7] = 9
# See Plot A
# Let's filter out all values larger than 2 and less than 6.
index1 = img1 > 2
index2 = img1 < 6
compound_index = index1 & index2
# The compound statement can alternatively be written as
compound_index = (img1 > 3) & (img1 < 7)
img2 = np.copy(img1)
img2[compound_index] = 0
# See Plot B.
# Making the boolean arrays even more complex
index3 = img1 == 9
index4 = (index1 & index2) | index3
img3 = np.copy(img1)
img3[index4] = 0
# See Plot C.